
namespace NS.Extranet.ADFSClaimsProvider
{
    //------------------------------------------------------------------------------
    // <auto-generated>
    //     This code was generated by a tool.
    //     Runtime Version:4.0.30319.18449
    //
    //     Changes to this file may cause incorrect behavior and will be lost if
    //     the code is regenerated.
    // </auto-generated>
    //------------------------------------------------------------------------------

    // 
    // This source code was auto-generated by xsd, Version=4.0.30319.33440.
    // 


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute("Users", Namespace = "", IsNullable = false)]

    public partial class ADFSUsers
    {

        private ADFSUser[] itemsField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("User", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ADFSUser[] Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class ADFSUser
    {

        private string notExportedField;

        private string emptyNotExportedField;

        private string ppl_idField;

        private string ppl_name_firstField;

        private string ppl_name_lastField;

        private string ppl_nameField;

        private string ppl_name_sortField;

        private string ppl_phone_directField;

        private string ppl_org_departmentField;

        private string ppl_job_titleField;

        private string ppl_rp_manager_idField;

        private string ppl_url_photoField;

        private string ppl_url_site_redirectField;

        private string ppl_emailField;

        private string ppl_phone_mobileField;

        private string ppl_faxField;

        private string ppl_loc_officeField;

        private string ppl_loc_countryField;

        private string ppl_job_categoryField;

        private string ppl_job_roleField;

        private string ppl_id_tkField;

        private string ppl_job_role_geo_respField;

        private string ppl_loc_regionField;

        private string ppl_loc_office_addressField;

        private string ppl_office_floor_noField;

        private string ppl_office_room_noField;

        private string ppl_cost_locationField;

        private string ppl_job_role_dept_functField;

        private string ppl_org_practice_group_globalField;

        private string ppl_org_practice_group_global_allField;

        private string ppl_org_practice_group_localField;

        private string ppl_org_practice_group_local_allField;

        private string ppl_name_localField;

        private string ppl_is_valid_adField;

        private string ppl_is_active_tkField;

        private string ppl_job_lawyerField;

        private string ppl_job_firmField;

        private UsersUserPpl_exp_lang_name[] ppl_exp_lang_nameField;

        public string SearchableTerms
        {
            get;
            set;
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NotExported
        {
            get
            {
                return this.notExportedField;
            }
            set
            {
                this.notExportedField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string EmptyNotExported
        {
            get
            {
                return this.emptyNotExportedField;
            }
            set
            {
                this.emptyNotExportedField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ppl_id
        {
            get
            {
                return this.ppl_idField;
            }
            set
            {
                this.ppl_idField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ppl_name_first
        {
            get
            {
                return this.ppl_name_firstField;
            }
            set
            {
                this.ppl_name_firstField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ppl_name_last
        {
            get
            {
                return this.ppl_name_lastField;
            }
            set
            {
                this.ppl_name_lastField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ppl_name
        {
            get
            {
                return this.ppl_nameField;
            }
            set
            {
                this.ppl_nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ppl_name_sort
        {
            get
            {
                return this.ppl_name_sortField;
            }
            set
            {
                this.ppl_name_sortField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ppl_phone_direct
        {
            get
            {
                return this.ppl_phone_directField;
            }
            set
            {
                this.ppl_phone_directField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ppl_org_department
        {
            get
            {
                return this.ppl_org_departmentField;
            }
            set
            {
                this.ppl_org_departmentField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ppl_job_title
        {
            get
            {
                return this.ppl_job_titleField;
            }
            set
            {
                this.ppl_job_titleField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ppl_rp_manager_id
        {
            get
            {
                return this.ppl_rp_manager_idField;
            }
            set
            {
                this.ppl_rp_manager_idField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ppl_url_photo
        {
            get
            {
                return this.ppl_url_photoField;
            }
            set
            {
                this.ppl_url_photoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ppl_url_site_redirect
        {
            get
            {
                return this.ppl_url_site_redirectField;
            }
            set
            {
                this.ppl_url_site_redirectField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ppl_email
        {
            get
            {
                return this.ppl_emailField;
            }
            set
            {
                this.ppl_emailField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ppl_phone_mobile
        {
            get
            {
                return this.ppl_phone_mobileField;
            }
            set
            {
                this.ppl_phone_mobileField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ppl_fax
        {
            get
            {
                return this.ppl_faxField;
            }
            set
            {
                this.ppl_faxField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ppl_loc_office
        {
            get
            {
                return this.ppl_loc_officeField;
            }
            set
            {
                this.ppl_loc_officeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ppl_loc_country
        {
            get
            {
                return this.ppl_loc_countryField;
            }
            set
            {
                this.ppl_loc_countryField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ppl_job_category
        {
            get
            {
                return this.ppl_job_categoryField;
            }
            set
            {
                this.ppl_job_categoryField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ppl_job_role
        {
            get
            {
                return this.ppl_job_roleField;
            }
            set
            {
                this.ppl_job_roleField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ppl_id_tk
        {
            get
            {
                return this.ppl_id_tkField;
            }
            set
            {
                this.ppl_id_tkField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ppl_job_role_geo_resp
        {
            get
            {
                return this.ppl_job_role_geo_respField;
            }
            set
            {
                this.ppl_job_role_geo_respField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ppl_loc_region
        {
            get
            {
                return this.ppl_loc_regionField;
            }
            set
            {
                this.ppl_loc_regionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ppl_loc_office_address
        {
            get
            {
                return this.ppl_loc_office_addressField;
            }
            set
            {
                this.ppl_loc_office_addressField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ppl_office_floor_no
        {
            get
            {
                return this.ppl_office_floor_noField;
            }
            set
            {
                this.ppl_office_floor_noField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ppl_office_room_no
        {
            get
            {
                return this.ppl_office_room_noField;
            }
            set
            {
                this.ppl_office_room_noField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ppl_cost_location
        {
            get
            {
                return this.ppl_cost_locationField;
            }
            set
            {
                this.ppl_cost_locationField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ppl_job_role_dept_funct
        {
            get
            {
                return this.ppl_job_role_dept_functField;
            }
            set
            {
                this.ppl_job_role_dept_functField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ppl_org_practice_group_global
        {
            get
            {
                return this.ppl_org_practice_group_globalField;
            }
            set
            {
                this.ppl_org_practice_group_globalField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ppl_org_practice_group_global_all
        {
            get
            {
                return this.ppl_org_practice_group_global_allField;
            }
            set
            {
                this.ppl_org_practice_group_global_allField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ppl_org_practice_group_local
        {
            get
            {
                return this.ppl_org_practice_group_localField;
            }
            set
            {
                this.ppl_org_practice_group_localField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ppl_org_practice_group_local_all
        {
            get
            {
                return this.ppl_org_practice_group_local_allField;
            }
            set
            {
                this.ppl_org_practice_group_local_allField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ppl_name_local
        {
            get
            {
                return this.ppl_name_localField;
            }
            set
            {
                this.ppl_name_localField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ppl_is_valid_ad
        {
            get
            {
                return this.ppl_is_valid_adField;
            }
            set
            {
                this.ppl_is_valid_adField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ppl_is_active_tk
        {
            get
            {
                return this.ppl_is_active_tkField;
            }
            set
            {
                this.ppl_is_active_tkField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ppl_job_lawyer
        {
            get
            {
                return this.ppl_job_lawyerField;
            }
            set
            {
                this.ppl_job_lawyerField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ppl_job_firm
        {
            get
            {
                return this.ppl_job_firmField;
            }
            set
            {
                this.ppl_job_firmField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ppl_exp_lang_name", Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true)]
        public UsersUserPpl_exp_lang_name[] ppl_exp_lang_name
        {
            get
            {
                return this.ppl_exp_lang_nameField;
            }
            set
            {
                this.ppl_exp_lang_nameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class UsersUserPpl_exp_lang_name
    {

        private string valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }


       
    }
}